### ISSUE TITLE
Add WildWins Lottery problem, tests, and description

### ISSUE THREAD

**Issue by chrismejia** [chrismejia/intro-to-code-js#5]
# Tasks

- [ ] Problem Description
- [ ] Tests & Test Data

## Rules

- [ ] 2 like and 1 unlike amount, win 0
- [ ] 3 like amounts, win that amount
- [ ] 2 like amounts and a 3X, win triple the prize
- [ ] Get a WILD, win both other prizes
