### ISSUE TITLE
[0X-Guide] Simplify repo branch structure - 1st 2024 problem batch

### ISSUE THREAD

**Issue by chrismejia** [chrismejia/intro-to-code-js#7]
## Idea

Two branches:

- main (no answers)
- 0X-Guide (answers, WIP, docs, ideas)

## Main Tasks

- [x] Update all instructions
- [x] Extract each problem into own files
- [x] Update all problem jsdocs
- [x] Update all examples
- [x] Extract all tests into own files
- [x] Test all tests
- [x] Update all test data

## Subtask status: #1

|       | 01     | 02     | 03     | 04     | 05     | 06     | 07     |
| ----- | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| Issue | ✅ #13 | ✅ #15 | ✅ #23 | ✅ #29 | ✅ #61 | ✅ #66 | ✅ #72 |

**Comment by chrismejia** [comment]
Closed by #93
